service: serverlessproject

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  #deploy resources in AWS using this profile which has set credentials earlier
  profile: serverlessUser

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    # A simple configuration for copying static assets
    - bucketName: serverlessbucketupload199 # required
      localDir: UploadData
functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: serverlessbucketupload199
