
service: creating-lambda-function

frameworkVersion: '3'

plugins:
  - serverless-deployment-bucket


provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  deploymentBucket:
    name: bucket-sonal-9960

functions:
  hello:
    handler: handler.hello
    name: my-first-lambda-${opt:stage}

 
